version: "3.9"

services:
  cardiomegaly-app:
    build:
      context: .

    container_name: cardiomegaly-app

    ports:
      - "5000:5000"

    volumes:
      - .:/app
      - ./models:/app/models

    environment:
      PYTHONUNBUFFERED: "1"

    restart: unless-stopped